tap "evandurfee/tap"

# Mono Fonts
cask "font-fira-code-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-hack-nerd-font"

# System Fonts
cask "font-lato"
cask "font-lexend"

# CLI tools
brew "evandurfee/tap/clip"

brew "bat"
brew "chezmoi"
brew "cosign"
brew "eza"
brew "fd"
brew "fzf"
brew "git-delta"
brew "just"
brew "jq"
brew "p7zip"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "yq"
brew "zoxide"

# Desktop Utils
# restart_service: true will also start the service on fresh install :)
brew "evandurfee/tap/freedesktop-color-scheme-monitor", restart_service: true
brew "evandurfee/tap/flatpak-installation-sync"
brew "syncthing", restart_service: true
# brew "bitwarden-cli" # Use the flatpak

# IDEs
cask "evandurfee/tap/clion-linux"
cask "evandurfee/tap/datagrip-linux"
cask "evandurfee/tap/goland-linux"
cask "evandurfee/tap/intellij-idea-linux"
cask "evandurfee/tap/pycharm-linux"
cask "evandurfee/tap/rider-linux"
cask "evandurfee/tap/rubymine-linux"
cask "evandurfee/tap/rustrover-linux"
# brew "mise"
# brew "uv"
